# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('salesman', 'Salesman'), ('customer', 'Customer')], default='customer', max_length=9),
            preserve_default=False,
        ),
    ]
