# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_profile_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_type',
            new_name='type',
        ),
    ]
