# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_squashed_0003_remove_wish_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='buget',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Budget'),
        ),
    ]
