# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='buget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Budget'),
            preserve_default=False,
        ),
    ]
