# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_squashed_0002_auto_20160522_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='brief',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Brief'),
        ),
    ]
