# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import imagefy.wishes.models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_auto_20160522_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='shopify_product_id',
            field=models.BigIntegerField(verbose_name='Shopify Product ID'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='photo',
            field=models.ImageField(upload_to=imagefy.wishes.models.random_filename, verbose_name='Photo'),
        ),
    ]
