# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wishes', '0002_auto_20160521_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 22, 0, 45, 18, 237716, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 22, 0, 45, 20, 11334, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
