# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_offer_salesman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
