# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0005_auto_20160522_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='detail',
        ),
        migrations.AddField(
            model_name='wish',
            name='brief',
            field=models.CharField(default='lorem ipsum', max_length=140, verbose_name='Brief'),
            preserve_default=False,
        ),
    ]
